name: Run AutoTransform

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "A JSON encoded schema to run"
        required: true
        type: string

permissions:
  contents: write

jobs:
  run-autotransform:
    runs-on: ubuntu-latest
    name: Run AutoTransform
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config user.name "AutoTransform Bot"
        git config user.email "nathro.autotransform@gmail.com"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install AutoTransform
      run: pip install AutoTransform==1.0.1a3
    - name: Install requirements
      run: pip install -r autotransform/requirements.txt
    - name: Run AutoTransform
      run: |
        git config user.name "AutoTransform Bot"
        git config user.email "nathro.autotransform@gmail.com"
        autotransform run --environment --verbose AUTO_TRANSFORM_SCHEMA
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        AUTO_TRANSFORM_SCHEMA: ${{ github.event.inputs.schema }}