name: Schedule AutoTransform

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  schedule-autotransform:
    runs-on: ubuntu-latest
    name: Schedule
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config --global user.name "AutoTransform Bot"
        git config --global user.email "nathro.autotransform@gmail.com"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install AutoTransform
      run: pip install AutoTransform==0.2.0a1
    - name: Install custom components
      run: pip install -r requirements.txt
    - name: Schedule AutoTransform
      run: autotransform schedule --verbose autotransform/schedule.json
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}