name: Run AutoTransform

on:
  workflow_dispatch:
    inputs:
      schema:
        description: "A JSON encoded schema to run"
        required: true
        type: string

jobs:
  run-autotransform:
    runs-on: ubuntu-latest
    name: Run
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config --global user.name "<<BOT NAME>>"
        git config --global user.email "<<BOT EMAIL>>"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install AutoTransform
      run: pip install AutoTransform==0.2.0a2
    - name: Install custom components
      run: pip install -r requirements.txt
    - name: Run AutoTransform
      run: autotransform run --verbose --environment AUTO_TRANSFORM_SCHEMA
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        AUTO_TRANSFORM_SCHEMA: ${{ github.event.inputs.schema }}