name: Docker Test Action

on:
  workflow_dispatch:

jobs:
  run-autotransform:
    runs-on: ubuntu-latest
    name: Run AutoTransform
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
    - name: Run docker
      run: autotransform/entrypoint.sh
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}
        COMMAND: run
        SCHEMA_NAME: Black Format
        MAX_SUBMISSIONS: 3
        REPO_DIR: ATTest