name: Schedule AutoTransform

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  schedule-autotransform:
    runs-on: ubuntu-latest
    name: Schedule AutoTransform
    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config --global user.name "AutoTransfor Bot"
        git config --global user.email "nathro.autotransform@gmail.com"
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install AutoTransform
      run: pip install AutoTransform==0.3.0a1
    - name: Install requirements
      run: pip install -r autotransform/requirements.txt
    - name: Schedule AutoTransform
      run: autotransform schedule --verbose autotransform/scheduler.json
      env:
        AUTO_TRANSFORM_CONFIG: environment
        AUTO_TRANSFORM_CREDENTIALS_GITHUB_TOKEN: ${{ secrets.AUTO_TRANSFORM_BOT_GITHUB_TOKEN }}